stages:
  data_ingestion:
    cmd: python src/modules/symbol_detection/faster_rcnn/pipeline/stage_01_data_ingestion.py
    deps:
      - src/modules/symbol_detection/faster_rcnn/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/test
 
  prepare_base_model:
    cmd: python src/modules/symbol_detection/faster_rcnn/pipeline/stage_02_prepare_base_model.py
    deps:
      - src/modules/symbol_detection/faster_rcnn/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifacts/trained_models

  model_evaluation:
    cmd: python src/modules/symbol_detection/faster_rcnn/pipeline/stage_03_model_evaluation_with_mlflow.py
    deps:
      - src/modules/symbol_detection/faster_rcnn/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
      - artifacts/data_ingestion/test
      - models/trained_model_fasterrcnn_6_11.pth
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    metrics:
    - scores.json:
        cache: false

       
