artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://drive.google.com/file/d/1-6haawpnaPTHxclM7WSrxhiO-Vwx2hRG/view?usp=drive_link
  local_data_file: artifacts/data_ingestion/test_data_set.zip
  unzip_dir: artifacts/data_ingestion


trained_models:
  root_dir: artifacts/trained_models
  model_path: artifacts/trained_models/trained_model_fasterrcnn_6_28.pth
  test_images_path: artifacts/data_ingestion/test
  annotations_path: artifacts/data_ingestion/annotations.csv
  faster_rcnn_files_path: artifacts/faster_rcnn_files
  
 
  