artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://drive.google.com/file/d/1N6biugOgu7Id53ayyOMt1j8iKTKYe0Zf/view?usp=sharing
  local_data_file: artifacts/data_ingestion/test_data_set.zip
  unzip_dir: artifacts/data_ingestion


base_model:
  root_dir: artifacts/trained_models
  base_model_path: models/trained_models/trained_model_fasterrcnn_6_11.pth
  test_images_path: artifacts/data_ingestion/test
  annotations_path: artifacts/data_ingestion/annotations.csv
  faster_rcnn_files_path: artifacts/faster_rcnn_files
  
 
  